apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-upbound-claim
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/csantanapr/crossplane-on-eks.git
    targetRevision: velero
    path: compositions/upbound-aws-provider/s3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
