apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-example
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/csantanapr/crossplane-on-eks.git
    targetRevision: velero
    path: examples/upbound-aws-provider/managed-resources/s3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
