apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: upbound-test-bucket
  annotations:
    crossplane.io/external-name: demo-crossplane-carrlos
  labels:
    testing.upbound.io/example-name: s3
spec:
  forProvider:
    region: us-west-2
    tags:
      Name: SampleBucket
  providerConfigRef:
    name: aws-provider-config
